# version: '3.8'

# services:
#   jenkins:
#     image: jenkins/jenkins:lts
#     user: root
#     ports:
#       - "8080:8080"
#     volumes:
#       - jenkins_home:/var/jenkins_home
#       - /var/run/docker.sock:/var/run/docker.sock
#     networks:
#       - app-net

#   app:
#     build: ./app
#     ports:
#       - "80:80"
#     networks:
#       - app-net

# volumes:
#   jenkins_home:

# networks:
#   app-net:

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock   # ğŸ”¹ permite Jenkins usar Docker do host
      - /usr/bin/docker:/usr/bin/docker             # ğŸ”¹ monta o binÃ¡rio do docker
    restart: unless-stopped

volumes:
  jenkins_home:
